name: clamss
favicon: null
layout_spectrum: 0.50318
typography_spectrum: 0.24509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5
  lightness: 0.6321375803090632
  saturation: 0.5
  rhythmicContrast: 0.78564193402417
purpose: []
